/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAgentTimeline: typeof import('./components/AiAgentTimeline.vue')['default']
    AiAssistantPanel: typeof import('./components/AiAssistantPanel.vue')['default']
    AiMarkdown: typeof import('./components/AiMarkdown.vue')['default']
    AiResultPreview: typeof import('./components/AiResultPreview.vue')['default']
    AiSettingsDialog: typeof import('./components/AiSettingsDialog.vue')['default']
    AppShell: typeof import('./components/AppShell.vue')['default']
    DataGrid: typeof import('./components/DataGrid.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileSidebar: typeof import('./components/FileSidebar.vue')['default']
    InspectorPanel: typeof import('./components/InspectorPanel.vue')['default']
    PixelOcean: typeof import('./components/PixelOcean.vue')['default']
    ResultChart: typeof import('./components/ResultChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlEditor: typeof import('./components/SqlEditor.vue')['default']
    TableBindingEditor: typeof import('./components/TableBindingEditor.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
